max_vocab_size = 50000
hidden_size = 64
use_batch_norm = true
dropout = 0.5
weight_decay = 0
lr = 0.001
batch_size = 32
max_epochs = 5
early_stopping = 1
output_dir = "./my_saved_model"
wandb_project = "nlp_module_3_assignment"
