_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 49
                - 51
                - 55
            "2":
                - 1
                - 49
                - 51
                - 55
            "3":
                - 1
                - 16
                - 23
                - 55
                - 62
            "4": 3.10.16
            "5": 0.19.7
            "8":
                - 5
            "12": 0.19.7
            "13": darwin-arm64
batch_size:
    value: 32
device:
    value: null
dropout:
    value: 0.5
early_stopping:
    value: 1
hidden_size:
    value: 64
lr:
    value: 0.001
max_epochs:
    value: 5
max_vocab_size:
    value: 50000
output_dir:
    value: null
use_batch_norm:
    value: true
wandb_project:
    value: nlp_module_3_assignment
weight_decay:
    value: 0
